services:
  postgres:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: mydatabase
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data
    networks:
      - custom_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin_password
    depends_on:
      - postgres
    volumes:
      - ./grafana_data:/var/lib/grafana
    networks:
      - custom_network

networks:
  custom_network:
    external: true
